### ISSUE TITLE
Not all requirements in requirements file

### ISSUE THREAD

**Issue by slinkymanbyday** [lunarca/SimpleEmailSpoofer#1]
I found I needed to install the following:
emailprotectionslib
dnslib
tldextract

**Comment by lunarca** [comment]
Hi,

These requirements are for the `spoofcheck` program. The version included in this repository has been deprecated and removed. The current `spoofcheck` program is now hosted at [https://github.com/bishopfox/spoofcheck](https://github.com/bishopfox/spoofcheck).
