### ISSUE TITLE
No module named emailprotectionslib.dmarc

### ISSUE THREAD

**Issue by InfoSecOne** [lunarca/SimpleEmailSpoofer#4]
When running
`sudo ./spoofcheck.py example.com`

Got error:
```
Traceback (most recent call last):
  File "./spoofcheck.py", line 7, in <module>
    import emailprotectionslib.dmarc as dmarclib
ImportError: No module named emailprotectionslib.dmarc
```
did
`sudo pip3 -r requirements.txt`

Python 2.7.6 (default, Jun 22 2015, 17:58:13)
[GCC 4.8.2] on linux2

**Comment by lunarca** [comment]
Hi, 

Sorry, the version of spoofcheck in this repository has been deprecated and removed. The current home for spoofcheck is [https://github.com/bishopfox/spoofcheck](https://github.com/bishopfox/spoofcheck). 

Additionally, it is my understanding that pip3 installs the Python 3 version of libraries. This would not be compatible with the Python 2.7 version that you are running.
